@startuml rentafacil
class Vehiculo {
    - placa
    - marca
    - modelo
    - precioDia
}
class Auto {
}
class Moto {
    - cilindrada
}
class Camioneta {
    - capacidadCarga
}
class Cliente {
    - id
    - nombre
    - dni
    - numeroTelefono
}
class Alquiler {
    - codigoAlquiler
    - fechaInicio
    - fechaFin
    - costoTotal
    - estado
    + calcularCostoTotal()
    + finalizarAlquiler()
}
class GestionRentaFacil {
    + agregarCliente()
    + agregarVehiculo()
    + registrarAlquiler()
    + finalizarAlquiler()
}
Auto --> Vehiculo
Moto --> Vehiculo
Camioneta --> Vehiculo
Cliente "1" o--> "0..3" Alquiler
Alquiler "1" o--> "1..*" Vehiculo
GestionRegistro "1" o--> "*" Cliente
GestionRegistro "1" o--> "*" Vehiculo
GestionRegistro "1" o--> "*" Alquiler
@enduml